var preguntasEconomia = [
['El oligopolio colusivo:', 'Actúa de manera similar a un monopolista.', 'Tiene una empresa líder que toma decisiones sin tener en cuenta a los demás.', 'Las empresas que lo componen bajan el precio cuando una de ellas lo hace también.', 'Ninguna empresa toma en cuenta lo que hacen las de la competencia para tomar sus decisiones.', 1],
['Las empresas de un mercado de competencia monopolística:', 'Se encuentran con muchas barreras de entrada y de salida.', 'Producen un bien que no está claramente diferenciado.', 'A largo plazo se situaran en un lugar en el que conseguirán beneficios extraordinarios.', 'Son muy numerosas.', 4],
['La siguiente expresión: “Una empresa puede estar en equilibrio aunque tenga pérdidas”, es:', 'Sólo se puede estar en equilibrio cuando se tienen beneficios.', 'Verdadera.', 'Falsa.', 'Estará en desequilibrio hasta que gane dinero.', 2],
['El desempleo cíclico:', 'Se debe a que la oferta agregada es inferior a la demanda agregada.', 'Es la tasa natural de desempleo.', 'Es solamente la tasa de desempleo debida al ciclo.', 'Se da cuando hay una producción inferior a la de pleno empleo.', 3],
['El monopolio:', 'Es más beneficioso para los consumidores que el mercado de competencia perfecta.', 'Es menos beneficioso para los consumidores que el mercado de competencia perfecta.', 'Está apoyado por la legislación comunitaria.', 'Ninguna de las respuestas es correcta.', 2],
['Los datos de la Encuesta de Población Activa:', 'Suelen ser inferiores a los que da el INEM.', 'Son comparables con los datos de empleo del resto de países de la Unión Europea.', 'No se utilizan demasiado.', 'Se extraen de las personas que se registran en el desempleo.', 2],
['La suma de la tasa de desempleo y la de empleo:', 'Es siempre igual a la tasa de actividad.', 'Es siempre menor que la tasa de actividad.', 'Es siempre cien.', 'Puede dar cualquier cifra.', 3],
['Forman la población activa:', 'Todos aquellos que están ocupando un puesto de trabajo en el momento actual.', 'Aquellos que no tienen empleo pero están en edad de trabajar.', 'Las personas que tienen edad de trabajar y desean hacerlo.', 'Toda la población menos los discapacitados.', 3],
['El Producto Interior Neto [PIN]:', 'Es el mismo que el PIB.', 'No incluye los impuestos indirectos.', 'Incorpora la renta de los españoles en el extranjero.', 'Sustrae la depreciación de los bienes de capital.', 4],
['Una de las siguientes metas no es un objetivo macroeconómico:', 'La estabilidad de precios.', 'La seguridad del abastecimiento.', 'La equidad.', 'El crecimiento económico.', 2],
['Uno de los siguientes problemas no puede ser considerado como una cuestión macroeconómica:', 'El crecimiento económico de un país.', 'El crecimiento de los precios en la Unión Europea.', 'La bajada de ventas de los automóviles.', 'El desempleo de un país.', 3],
['El PNB se diferencia del PNN en que el primero de ellos incluye:', 'Los impuestos directos.', 'Las amortizaciones.', 'Las transferencias del Estado.', 'Los intereses de la deuda pública.', 2],
['El PIB a precios de los factores:', 'Suele ser menor que el PIB a precios de mercado.', 'Suele ser mayor que el PIB a precios de mercado.', 'Suele ser igual que el PIB a precios de mercado.', 'No tiene ninguna relación con el PIB a precios de mercado.', 1],
['El PIB real:', 'Descuenta la inflación.', 'No tiene en cuenta la inflación.', 'Es siempre mayor que el nominal.', 'Utiliza los precios corrientes.', 1],
['Si el PIB real de un país es 110 y su PIB nominal es 112:', 'Podríamos hallar sin problemas el deflactor del PIB de ese año.', 'Nos es imposible hallar el deflactor del PIB de ese año.', 'Necesitamos conocer el año base para poder sacar alguna conclusión con estas cifras.', 'Podemos estar seguros de que los precios han bajado.', 1],
['Una de las siguientes funciones no se le asigna al Estado en una economía mixta:', 'Estabilizar la economía.', 'Regular la actividad económica.', 'Ofrecer bienes y servicios para satisfacer necesidades.', 'Redistribuye las rentas.', 3],
['Una de las siguientes políticas no puede considerarse coyuntural:', 'La política de rentas.', 'La política fiscal.', 'La política monetaria.', 'La política de infraestructuras.', 4],
['Los problemas medioambientales producidos por las actividades económicas:', 'Producen disfunciones en la competencia.', 'Pueden catalogarse como males públicos.', 'Se solucionan a través de políticas fiscales.', 'Son externalidades negativas que hay que corregir.', 4],
['Uno de los siguientes gastos puede considerarse que no construye el Estado de bienestar:', 'El gasto en salud.', 'El gasto en educación.', 'El gasto en infraestructuras públicas.', 'Los subsidios de desempleo.', 3],
['El consumo de una familia:', 'Depende de toda la renta de la familia.', 'Se incrementa cuando paga más impuestos.', 'Disminuye a medida que baja la cantidad ahorrada.', 'Depende de la renta disponible de la familia.', 4],
['El volumen de inversión aumenta cuando:', 'Aumenta la renta nacional.', 'Bajan los tipos de interés.', 'Aumenta el PNB.', 'El ciclo económico es de depresión económica.', 1],
['La inversión:', 'Se incrementa ante un aumento de los tipos de interés.', 'Será mayor cuando menor sea la renta de un determinado país.', 'Se incrementará con unas mejores expectativas empresariales.', 'Será mayor cuando mayores sean los costes.', 3],
['Una política fiscal expansiva:', 'Traslada la demanda agregada a la derecha.', 'Traslada la demanda agregada a la izquierda.', 'Traslada la oferta agregada a la derecha.', 'Traslada la oferta agregada a la izquierda.', 2],
['Con un impuesto progresivo:', 'Se paga menor cantidad de dinero cuando más renta se tiene.', 'Se paga mayor porcentaje cuando más renta se tiene.', 'Se paga la misma cantidad se tenga la renta que se tenga.', 'Ninguna de las otras es correcta.', 2],
['La política fiscal:', 'Afecta a la oferta agregada.', 'Afecta a la demanda de dinero.', 'Afecta a la demanda agregada.', 'Afecta a la oferta monetaria.', 4],
['El déficit público:', 'Se financia a través de la emisión de deuda pública.', 'Se financia a través de la emisión de dinero por parte del Banco Central Europeo.', 'Se financia a través de los impuestos.', 'No se da nunca.', 1],
['Una política fiscal contractiva se aplicará:', 'Cuando exista mucho desempleo.', 'En momentos de recesión económica.', 'Para incrementar la producción agregada.', 'Cuando se ha alcanzado la producción potencial y hay peligro de inflación.', 4],
['El multiplicador de la inversión [o gasto público] es mayor cuando:', 'Mayor es la propensión a ahorrar.', 'Mayor es la propensión marginal a consumir.', 'Mayor es el gasto público.', 'Mayor es el volumen de impuestos.', 2],
['Un aumento de la tasa impositiva:', 'Afecta negativamente a la demanda agregada.', 'Afecta positivamente a la demanda agregada.', 'No tiene efecto alguno sobre la demanda agregada.', 'Aumenta la renta disponible.', 1],
['Hay efecto multiplicador cuando aumenta el gasto público porque:', 'El consumo depende de la renta.', 'El gasto público puede mejorar las infraestructuras.', 'El gasto público es un componente de la demanda agregada.', 'El gasto público es un instrumento de la política fiscal.', 1],
['Una política fiscal es eficaz:', 'Siempre.', 'Nunca.', 'Cuando la curva de oferta agregada es vertical.', 'Cuando la curva de oferta agregada es horizontal.', 4],
['Un aumento de la tasa impositiva:', 'Disminuye el efecto multiplicador.', 'No afecta al efecto multiplicador.', 'El efecto final dependerá de la pendiente de la curva de oferta.', 'Aumenta el efecto multiplicador.', 2],
['Las tarjetas de débito:', 'Son lo mismo que las tarjetas de crédito.', 'Salen más caras que las tarjetas de crédito.', 'Se diferencian de las de crédito en el límite del crédito.', 'Se diferencian de las de crédito en que en ellas se retira el dinero en el momento del intercambio.', 4],
['Una de las siguientes respuestas no es una función del dinero:', 'Cesta de  la compra.', 'Depósito de valor.', 'Unidad de cuenta.', 'Medio de pago.', 1],
['Los tipos de interés que cobran los bancos y cajas de ahorros son:', 'Mayores que el Euribor.', 'Menores que el Euribor.', 'Iguales al Euribor', 'Ninguna es correcta.', 1],
['Un descenso de los tipos de interés afecta al equilibrio macroeconómico:', 'Aumentando los precios y la producción.', 'Disminuyendo los precios y la producción.', 'Aumentando los precios y disminuyendo la producción.', 'Disminuyendo los precios y aumentado la producción.', 1],
['El Euribor depende del:', 'Comportamiento del mercado del dinero.', 'De las decisiones de los respectivos gobiernos nacionales.', 'Del gasto de cada país.', 'Ninguna es correcta.', 1],
['Cuando los Bancos Centrales venden Deuda Pública, la oferta monetaria:', 'Aumenta.', 'Disminuye.', 'Todas las respuestas son correctas.', 'Ni  aumenta ni disminuye.', 1],
['Los Intermediarios Financieros bancarios son:', 'Los Bancos', 'Las Cajas de Ahorro', 'Las Cooperativas de Crédito', 'Todas las respuestas son correctas', 4],
['Una de las siguientes metas no es un objetivo macroeconómico:', 'La estabilidad de precios.', 'El crecimiento económico.', 'La seguridad del abastecimiento.', 'La equidad.', 3],
['Entre las características de los Activos Financieros, encontramos:', 'La Rentabilidad, que es el rendimiento que se obtiene del Activo', 'La Rentabilidad puede ser Fija o Variable', 'El Riesgo o la Liquidez', 'Todas las respuestas son ciertas', 4],
['Respecto a los Tipos de Interés y la Bolsa', 'Si baja el Tipo de Interés, los inversores acuden a la Bolsa', 'Si baja el Tipo de Interés, los inversores salen de la Bolsa', 'Bolsa y Tipos de Interés no se relacionan', 'Si sube el Tipo de Interés, se invierte más en Bolsa', 1],
['El PIB a precios de los  factores:', 'Suele ser mayor que el PIB a precios de mercado.', 'Suele ser menor que el PIB a precios de mercado.', 'Suele ser igual que el PIB a precios de mercado.', 'No tiene ninguna relación con el PIB a precios de mercado.', 2],
['El Producto Interior Neto [PIN]:', 'No incluye los impuestos indirectos.', 'Introduce la renta de los españoles en el extranjero.', 'Sustrae la depreciación de los bienes de capital.', 'Es el mismo que el PIB.', 3],
['No es considerado como una cuestión macroeconómica:', 'El crecimiento económico de un país.', 'El crecimiento de los precios en la Unión Europea.', 'La bajada de ventas de los comercios.', 'El desempleo de un país.', 3],
['El PIB real:', 'No tiene en cuenta la inflación.', 'Es siempre mayor que el nominal.', 'Utiliza los precios corrientes.', 'Descuenta la inflación.', 4],
['Si el Euro entrase en un proceso continuo de depreciación', 'Los productos de la zona euro  se abaratarían para los extranjeros', 'Las importaciones se encarecerían', 'Los inversores de la zona euro en el exterior podrían resultar beneficiados', 'Todas las respuestas son ciertas', 4],
['Son factores que influyen en la apreciación o depreciación de una moneda,', 'El diferencial de inflación', 'El diferencial de tipos de interés', 'El diferencial de crecimiento económico', 'Todas las respuestas son ciertas', 4],
['La falta de competencia:', 'No puede darse en un mercado ya que va en contra de su esencia.', 'Es una consecuencia no deseada del funcionamiento del mercado.', 'Tiene efectos negativos sobre las empresas que la sufren.', 'Es defendida por el Estado.', 2],
['Una de las siguientes funciones no se le asigna al Estado en una economía mixta:', 'Regular la actividad económica.', 'Ofrecer bienes y servicios para satisfacer necesidades.', 'Estabilizar la economía.', 'Redistribuye las rentas.', 2],
['Uno de los siguientes bienes puede considerarse un bien público puro:', 'Una manzana.', 'La educación.', 'La sanidad.', 'El alumbrado de una calle.', 4],
['Una de las siguientes políticas no puede considerarse coyuntural:', 'La política monetaria.', 'La política de rentas.', 'La política de infraestructuras.', 'La política fiscal.', 3],
['Los avances tecnológicos:', 'Son las principales fuerzas que impulsan la globalización.', 'Van paralelos a la globalización pero sin relación.', 'Son la base de la globalización cultural.', 'Permiten los intercambios comerciales.', 1],
['Una economía pura de mercado:', 'Consigue siempre una sociedad igualitaria.', 'Potencia la competencia entre las empresas que participan en ella.', 'Proporciona todos los bienes necesarios para la sociedad.', 'Ninguna de las otras contestaciones es correcta.', 4]
];
var preguntasHistoria = [
['¿Qué rey español decretó la expulsión de los moriscos en el año 1609?', 'Felipe II', 'Felipe III', 'Felipe IV', 'Felipe V', 2],
['¿En qué año pisó el hombre por primera vez la superficie lunar?', '1969', '1967', '1959', '1966', 1],
['¿Qué rey bárbaro saqueó Roma en el año 455 d.C.?', 'Atila, rey de los Hunos', 'Alarico, rey de los visigodos', 'Genserico, rey de los vándalos', 'Requiario, rey de los suevos.', 3],
['¿Frente a qué tropas se enfrentó la coalición cristiana comandada por Don Juan de Austria en la batalla de Lepanto?', 'A los calvinistas.', 'A los musulmanes que dominaban Tierra Santa.', 'Al imperio Otomano', 'A los bereberes del Norte de África', 3],
['¿Cómo fue destronado el rey visigodo Wamba?', 'Fue asesinado', 'Abdicó en su sobrino Égica', 'Fue derrotado en la batalla de Guadalete', 'Fue envenenado y decalvado', 4],
['¿Cómo se llamaba el primer avión que arrojó una bomba atómica?', 'Total Destruction', 'Enola Gay', 'Sayonara Baby', 'Bing Bang Theory', 2],
['Los visigodos abandonaron la fe arriana y se convirtieron al catolicismo gracias a la acción del rey:', 'Chindasvinto', 'Recadero', 'Wamba', 'Roderico', 2],
['Gonzalo Fernández de Córdoba ha pasado a la historia con el sobrenombre de:', 'El invencible', 'El Felón', 'El Ilustrado', 'El Gran Capitán', 4],
['En el conocido como desastre de Annual del año 1921, las tropas españolas fueron derrotadas por los soldados de:', 'Tariq ibn Ziyad', 'Abd el-Krim', 'Almanzor', 'Abderramán II', 2],
['Se considera que el primer desembarco aeronaval de la historia fue el de:', 'Alhucemas.', 'Normandía.', 'Sicilia.', 'Bahía Cochinos.', 1],
['El rey visigodo Eurico invadió la Hispania romana y conquistó Tarraco en el año:', '511 d.C.', '474 d.C.', '410 d.C.', '451 d.C.', 2],
['¿Cómo perdió España sus últimas posesiones en Oceanía [las islas Marianas, Carolinas y Palaos]?', 'Se independizaron.', 'Fueron cedidas a los EE.UU tras la guerra de Cuba.', 'Fueron vendidas a Alemania.', 'Fueron invadidas por Japón durante la II Guerra Mundial.', 3],
['¿Qué acontecimiento desencadenó la entrada de los EE.UU en la guerra hispano-cubana del 98?', 'El asesinato del embajador norteamericano en Madrid.', 'El bloqueo comercial de España a los productos norteamericanos.', 'El hundimiento del trasatlántico Lusitania.', 'El hundimiento del acorazado Maine.', 4],
['La teoría de la separación de poderes [legislativo, ejecutivo y judicial] fue elaborada por:', 'Napoleón Bonaparte', 'Fernando VII', 'Montesquieu', 'Robespierre', 3],
['Bismark es considerado como:', 'El máximo impulsor de la unificación alemana del XIX.', 'El discípulo más aventajado de Wagner', 'El cofundador de la Sociedad de Naciones', 'El inventor del motor de explosión.', 1],
['La revolución francesa estalló en el año:', '1802', '1703', '1789', '1864', 3],
['Leónidas I fue rey de:', 'Esparta', 'Atenas', 'Troya', 'Macedonia', 1],
['El tratado de San Ildefonso firmado en  1800, significó, por parte de España:', 'La cesión de Gibraltar a los ingleses.', 'La cesión de la Florida a los EE.UU.', 'La cesión de la Luisiana a los franceses.', 'La independencia de México.', 3],
['Los sumerios inventaron:', 'La rueda y la cerveza', 'La pólvora y la astrología', 'La brújula y la escritura', 'La rotación de cultivos y la lente de aumento', 1],
['Juana de Arco nació en:', 'Rusia', 'Francia', 'Inglaterra', 'Arcos de la Frontera', 2],
['Rosa de Luxemburgo fue una importante:', 'Política marxista de origen polaco.', 'Miembro del PSOE durante la I República.', 'Escritora gallega', 'Diplomática de origen francés.', 1],
['El general romano Aecio fue asesinado a punta de espada por:', 'Atila el Huno', 'El emperador Valentiniano', 'Genserico', 'Julio Cesar', 2],
['Los almogávares fueron:', 'Los primeros musulmanes que invadieron España en el siglo VIII', 'Los judíos que vivían en tierras musulmanas', 'Tropas pertenecientes a la Corona de Aragón', 'Las tropas de élite del Califato de Córdoba.', 3],
['En la batalla de “Little Big Horn” entre las tropas de los Estados Unidos y los Sioux, perdió la vida:', 'El jefe indio Toro Sentado', 'Buffalo Bill', 'El general Caster', 'Billy el Niño', 3],
['¿En qué año los vikingos realizaron su primera incursión de ataque y saqueo a las costas de Gran Bretaña?', '1100', '793', '867', '543', 2],
['La guerra de los treinta años enfrentó a:', 'Francia y España', 'Inglaterra y Escocia', 'Prácticamente a toda Europa', 'España y EE.UU.', 3],
['¿Cuál fue el primer ejército profesional de la Historia?', 'El romano', 'El asirio', 'El egipcio', 'El visigodo', 2],
['¿Entre qué años tuvo lugar la guerra de secesión americana?', '1854-1859', '1910-1915', '1775-1783', '1861-1865', 4],
['¿Quién fue maestro de Alejandro Magno durante su juventud?', 'Eudoxo de Cnio.', 'Platón.', 'Aristóteles.', 'Sófocles.', 3],
['¿Cuál fue el pretexto esgrimido por los EE.UU. para entrar en guerra con Vietnam?', 'El ataque vietnamita al destructor USS Maddox', 'El secuestro del embajador norteamericano en Saigón.', 'El asesinato de una misionera norteamericana.', 'El derrocamiento del presidente vietnamita Ho Chi Minh por parte de los revolucionarios comunistas.', 1],
['¿Con qué pueblo establecieron relaciones culturales y comerciales los tartesios entre los siglo VIII y VII a.C?', 'Griego', 'Fenicio', 'Celta', 'Cartaginés', 2],
['¿Cuál fue la principal actividad económica del pueblo fenicio?', 'Agricultura', 'Ganadería', 'Orfebrería', 'Comercio marítimo', 4],
['¿Cuál fue el último rey de los Tartessos?', 'Argantonio', 'Gárgoris', 'Habis', 'Gerión', 1],
['¿De dónde procedían los pueblos celtas que llegaron a la península entre los siglos VIII y VI a.C.?', 'Mediterráneo Oriental', 'Norte de África', 'Islas Británicas', 'Centroeuropa', 4],
['¿De qué zona de España son propios los monumentos megalíticos conocidos como taulas, talayots o navetas?', 'Aragón', 'Islas Baleares', 'Cataluña', 'Comunidad Valenciana', 2],
['La desamortización de Pascual Madoz:', 'Solucionó el problema de la propiedad', 'Repartió la propiedad pero no solucionó el problema', 'Acabó con el atraso agrícola', 'Ninguna de las respuestas es correcta', 2],
['El carlismo defiende:', 'Sociedad estamental, poder de la Iglesia y foros', 'Despotismo ilustrado', 'Los privilegios estamentales', 'La monarquía de Isabel  II', 1],
['Al final de la guerra los carlistas se dividen en:', 'Neocatólicos y progresistas', 'Intransigentes y transaccionistas', 'Moderados y progresistas', 'Ninguna de las respuestas es correcta', 2],
['La dictadura tecnocrática de Bravo Murillo:', 'Intenta fomentar la democratización política', 'Favorece el desarrollo económico', 'Fomenta el desarrollo económico a costa de las libertades políticas', 'Ninguna de las respuestas es correcta', 3],
['Los partidos políticos españoles en el reinado de Isabel II representaban a:', 'El pueblo llano', 'La nobleza', 'La alta burguesía', 'Al  clero', 3],
['¿En qué continente apareció el primer homínido?', 'Asia', 'América', 'África', 'Europa', 3],
['¿Dónde ubicas el Mesolítico?', 'Entre la historia antigua y media', 'Entre el paleolítico y el neolítico', 'Entre el mundo antiguo y el prehistórico', 'Ninguna de las respuestas es correcta', 2],
['Las reformas económicas  de Mendizábal se caracterizan por:', 'Intentar implantar el liberalismo económico', 'Beneficiar a los grupos privilegiados', 'Se basan en la construcción del ferrocarril', 'Ninguna de las respuestas es correcta', 1],
['El Australopitecus apareció sobre la tierra:', 'Hace 1 millón de años', 'Hace 150 millones de años', 'Hace 5 millones de años', 'Hace 10 mil años', 3],
['¿Qué hecho determina la invención y difusión de la escritura?', 'La vida nómada', 'La sedentarización de la sociedad', 'El nacimiento de las primeras sociedades civilizadas', 'El fin de la sociedad recolectora', 3],
['¿Cuándo comenzó el Paleolítico?', 'Cuando apareció el hombre sobre la tierra', 'Cuando la tierra se formó.', 'Cuando el hombre invento el fuego', 'Cuando el hombre descubrió la agricultura', 1],
['Marca respuesta incorrecta: La constitución de 1869:', 'Reconoce la soberanía popular.', 'Establece el sufragio universal a partir de los 18 años.', 'Reconoce las libertades democráticas básicas y la libertad religiosa.', 'Las Cortes eran bicamerales', 2],
['¿En qué año asumió la corona Alfonso XIII?', '1931', '1905', '1903', '1902', 4],
['¿Cuál fue la capital del Emirato que se formó en Al-Ándalus?', 'Sevilla', 'Cádiz', 'Córdoba', 'Málaga', 3],
['¿En qué año estalló el movimiento revolucionario denominado La Gloriosa?', '1868', '1968', '1936', '1945', 1],
['Durante el inicio del Sexenio Democrático, ¿quién fue el presidente del gobierno?', 'Serrano', 'Prim', 'Almirante Topete', 'Estanislao Figueras', 2],
['¿En qué año derrotó Don Pelayo a los musulmanes?', '789', '756', '590', '722', 4],
['¿Dónde solía residir la corte de la Corona de Aragón?', 'En Lleida', 'En Gerona', 'En Barcelona', 'En Tarragona', 3],
['¿En qué siglo se creó la Universidad de Salamanca, primera universidad española?', 'Siglo XV', 'Siglo VII', 'Siglo XI', 'Siglo XIII', 4],
['¿Quiénes fueron derrotados en la Batalla de las Navas de Tolosa?', 'Catalanes', 'Almohades', 'Cristianos', 'Gallegos', 2],
['¿Con quién alcanzó  su máximo apogeo la Escuela de Traductores?', 'Alfonso X', 'Alfonso I', 'Fernando V', 'Carlos II', 1],
['¿A qué figura encomendó el rey la función de controlar los municipios?', 'La figura del corregidor', 'La figura del primer ministro', 'La figura del juez', 'La figura del maestro', 1],
['¿En qué año se produjo la conquista de Granada?', '1456', '1420', '1567', '1492', 4],
['¿Cuál fue el año en el que la peste negra alcanzó más fuerza?', '1356', '1348', '1254', '1360', 2],
['¿En qué Edad se llevó a cabo la Conquista Musulmana?', 'Edad Moderna', 'Edad Antigua', 'Edad Media', 'Edad Contemporánea', 3],
['¿En qué año se produjo la conquista de Granada?', '1456', '1420', '1567', '1492', 4],
['¿A qué figura encomendó el rey la función de controlar los municipios?', 'La figura del corregidor', 'La figura del primer ministro', 'La figura del juez', 'La figura del maestro', 1],
['¿Cómo terminó La Reconquista?', 'Con la conquista de Córdoba', 'Con la conquista de los Pirineos', 'Con la conquista de Murcia', 'Con la conquista de Granada', 4],
['¿En qué ciudad española se llevó a cabo la actividad traductora?', 'Málaga', 'Granada', 'Lleida', 'Toledo', 4],
['¿Qué territorios componían la Corona de Aragón?', 'El Principado de Cataluña y los Reinos de Aragón', 'Los Reinos de Castilla', 'El Reino de Badajoz', 'Valencia y Cataluña', 1],
['¿Qué característica presentaba la Corona de Aragón?', 'El republicanismo', 'La violencia', 'El bipartidismo', 'La diversidad territorial', 4],
['¿En qué siglo se creó la Generalitat?', 'Siglo XIV', 'Siglo XV', 'Siglo XI', 'Siglo XII', 1],
['¿Cómo se llamó la batalla entre el  ejército de Táriq y los visigodos en el año 711?', 'La batalla de San Pedro', 'La batalla del rio Guadalete', 'La batalla del rio Tajo', 'La batalla de Huesca', 2],
['¿Cuáles de los siguientes grupos sociales formaban parte de Al-Ándalus?', 'Asiáticos', 'Bereberes', 'Indios', 'Mozárabes', 2],
['¿Cuál de los siguientes órganos tenía competencia de gobierno y asesoraban al monarca durante la baja Edad Media?', 'Audiencia', 'Condestable', 'Consejo Real', 'Ministerio de gobierno', 3],
['El código que consiguió la unificación jurídica para que el monarca legislara sin contar con las cortes, se llamaba:', 'Código de las partidas', 'Código de Isabel', 'Código de Castilla', 'Código de las Américas', 1],
['En la baja Edad Media, Castilla no tuvo una capital permanente, pero la ciudad más importante fue:', 'Zamora', 'Valladolid', 'Salamanca', 'Burgos', 2],
['¿A dónde huyeron los nobles visigodos y eclesiásticos debido a la conquista musulmana?', 'Al Reino de Ávila', 'Al Reino de Francia', 'Al Reino de Asturias', 'Al Reino de Portugal', 3],
['¿Dónde se llevó a cabo la repoblación de las órdenes militares?', 'En La Mancha y Extremadura', 'En las Islas canarias y Baleares', 'En el  norte de Castellón y Teruel', 'En el sur de Sevilla', 1],
['¿Por qué es conocido Averroes?', 'Importante militar mozárabe', 'Importante arquitecto', 'Importante filósofo', 'Importante escultor de Al-Andalus', 3],
['¿Quiénes fueron los padres de Isabel II?', 'Fernando VII y María Cristina de Borbón', 'Alfonso XII y María Cristina de Borbón', 'Fernando VII y María Isabel de Borbón', 'Alfonso XII y María Isabel de Borbón', 1],
['¿Quién tomó Granada?', 'Alfonso I', 'Pelayo I', 'Los Reyes Católicos', 'Alejandro IV', 3],
['¿Cuáles fueron los principales núcleos de resistencia cristiana?', 'Navarra', 'Córdoba', 'Condado de Aragón y condado Catalán', 'Zamora', 1],
['Fecha de inicio de la dictadura del General Serrano:', '1902', '1869', '1874', '1803', 3],
['¿Cuánto duró el reinado de Amadeo de Saboya?', '2 años', '12 años', '22 años', '32 años', 1],
['¿Qué llevó a Isabel  II al exilio?', 'La muerte de su marido Fernando de Borbón', 'La revolución de La Gloriosa', 'La persecución de los republicanos', 'La muerte de su marido Francisco de Asís', 2],
['Periodo de reinado de Isabel II', '1833 – 1868', '1812 – 1848', '1823 – 1853', '1898 – 1923', 1],
['¿Cuánto duró el reinado de Alfonso XIII?', '1886 - 1931', '1902 - 1931', '1886 - 1902', '1923 – 1973', 1],
['¿Qué fue “La Gloriosa”?', 'La guerra que dio la victoria a España contra Cuba', 'La constitución de 1812', 'La revolución que se dio durante el reinado de Alfonso XII', 'Revolución de 1868', 4]
];

var preguntasFilosofia = [
['En Aristóteles, El Ser Puede definirse:', 'Por una lista de categorías', 'En cuanto a su propio ser', 'En cuanto a sus juicios', 'En ser y no ser', 1],
['Para Aristóteles, los conceptos Acto y Potencia:', 'Definen el espectro cromático de las cosas', 'Sirven para definir el movimiento', 'Definen la esencia de la Filosofía', 'Sirven para definir el mundo de los sentimientos', 2],
['Para Aristóteles, el concepto Logos:', 'Nombra lo que son las cosas', 'Nombra el ser intrínseco de las cosas', 'Es el principio del estudio de la gramática', 'Señala la parte de lo que conocemos de las cosas', 1],
['En su obra “Metafísica”, Aristóteles:', 'Se plantea por primera vez la existencia de Dios', 'Trata del conocimiento de los objetos', 'Habla sobre la formación del mundo', 'Se introduce en lo espiritual', 1],
['Entre las obras de Aristóteles, podemos citar:', 'Ética a Nicómano y Metafísica', 'Refutación a Pitágoras y El Simoposium', 'Teoría sobre el Universo, Espacio y Tiempo', 'El espectador y El mito de la Caverna', 1],
['¿En qué época nació Aristóteles?', 'A finales del S. III a.C', 'A principios del S. III a.C', 'A principios del S. IV a.C', 'A finales del S. IV a.C', 1],
['¿De quién fue alumno Aristóteles?', 'Anaxágonas', 'Sócrates', 'Platón', 'Zenón de Citio', 3],
['Aristóteles nació en:', 'Atenas', 'Estagira [Macedonia]', 'Asia Menor', 'Tagaste', 2],
['Tres obras importantes de Platón son:', 'Nóumenos, Fenóumenos y Retórica', 'Estética, Dialéctica y Psicología', 'Ética, Estética y Retórica', 'El Simposium, Fedro y La República', 4],
['Platón introduce el mito de Fedro y La Caverna en sus obras para:', 'Explicar la teoría del mundo en ambos casos', 'Explicar el origen del mundo en ambos casos', 'Fedro para explicar la Koinomía y la Caverna para el conocimiento de las cosas', 'Fedro para explicar el conocimiento de las cosas y la Cavernas para la Koinomía', 3],
['Las obras de Platón:', 'Se conservan casi enteras', 'Sólo se conservan algunas', 'Platón no dejó nada escrito', 'No se han encontrado hasta ahora', 1],
['El estilo literario de las obras de Platón son:', 'Unos diálogos en los que el protagonista suele ser Sócrates', 'Obras teatrales con Sócrates de protagonista', 'Unos versos en los que el protagonista suele ser Sócrates', 'Las tres respuestas  son verdaderas', 1],
['Platón fue alumno de:', 'Sócrates', 'Aristóteles', 'Filóstrato', 'Demócrito', 1],
['Platón fundó una escuela filosófica que se llamó:', 'Los Peripatéticos', 'Los Cínicos', 'Los Estoicos', 'La Academia', 1],
['Sócrates nació y murió en los años:', '582-507 ac', '427-347 ac', '384-322 ac', '470-399 ac', 4],
['¿Quién dio la definición más antigua de la filosofía?', 'Pitágoras', 'Freud', 'Sócrates', 'Demócrito', 1],
['Filósofo y matemático griego que afirmaba que la estructura del universo era aritmética y geométrica:', 'Platón', 'Pitágoras', 'Sócrates', 'Aristóteles', 2],
['Sócrates fue condenado a ingerir cicuta por:', 'Pervertir a sus discípulos por ayudarlos a parir conceptos e ideas', 'Ser un buen filósofo', 'Creer que la ciencia no existe', 'No pensar que liberaba a los individuos del control de los mitos', 1],
['Es filosofía cuando aborda el problema del ser; es una teoria del ser:', 'Epistemología', 'Los argumentos', 'La ontología', 'La filosofía', 3],
['¿Quién fue el primer filósofo que afirmó que la tierra era esférica?', 'Platón', 'Tales de Mileto', 'Pitágoras', 'Santo Tomás', 3],
['En la filosofía no basta con creer u opinar, es necesario:', 'Pensar', 'Adivinar', 'Argumentar', 'Estudiar', 3],
['La filosofía se presenta como _________ al momento de centrar su atención en la ciencia, para analizar y evaluar su estructura, su modo de producir hipótesis y teorías:', 'Epistemología', 'Argumental', 'Ontología', 'Filosofía', 1],
['Tanto Platón como Aristóteles señalaban que el ser humano no puede vivir más que en sociedad porque es un “zoon politikon” que quiere decir:', 'Animal político', 'Hombre', 'Bestia', 'Lobo', 1],
['Filósofo que define a Dios como pensamiento que se piensa en si mismo:', 'Aristóteles', 'Platón', 'Wilhelm Hegel', 'Descartes', 1],
['El término “filosofía”, significa:', 'Sabiduría', 'Amor', 'Amor a la sabiduría', 'Arte', 3],
['Filósofo que define la filosofía así: “lo que en un principio movió a los hombres a hacer las primeras indagaciones filosóficas fue, como lo que es hoy, la admiración”.', 'Ortega y Gasset', 'Luke', 'Pitágoras', 'Aristóteles', 4],
['Filósofo que propuso un sistema geocéntrico en el que la tierra era el centro del universo, mientras el sol y otros planetas giraban a su alrededor:', 'Spinoza', 'Descartes', 'Hume', 'Aristóteles', 4],
['¿Cuál es la finalidad de la filosofía como conocimiento de la realidad?', 'Es el mundo como totalidad de múltiples procesos; naturales, sociales e históricos', 'Crear pensamientos de cualquier cosa en los individuos', 'Los conocimientos científicos', 'Desarrollar nuevas etapas de estudio', 1],
['Método que  utiliza la ironía. La cual presenta una serie de preguntas al interlocutor para confundirlo, hacerlo caer en contradicción y hacerlo caer en su ignorancia:', 'Método socrático', 'Método cartesiano', 'Método crítico', 'Método hermenéutico', 1],
['A  los procedimientos para analizar la realidad que se aplica a múltiples campos de estudio, entre ellos la filosofía, se les conoce como:', 'Pasos', 'Guías', 'Métodos', 'Entradas', 3],
['Filósofo que escribió sobre formas de gobierno, la herencia del medio ambiente en la personalidad y la dicotomía entre el saber y la opinión:', 'Platón', 'Tales de Mileto', 'Séneca', 'Kant', 1],
['Método que entiende la crítica como el proceso por el cual la razón se vuelve sobre sí misma para conocer sus propios límites y las condiciones en que funda su propia validez:', 'Método socrático', 'Método cartesiano', 'Método crítico', 'Método fenomenológico', 3],
['Método de René Descartes que propone la búsqueda de la verdad, la duda metódica:', 'Método socrático', 'Método cartesiano', 'Método crítico', 'Método fenomenológico', 2],
['¿Cuál es la teoría filosófica que se centra en el estudio de los fenómenos, de los que percibimos con los sentidos?', 'Psicología', 'Ontología', 'Fisiología', 'Fenomenología', 4],
['¿Qué método fue desarrollado por Edmund Husserl, el cual toma como punto de partida la duda metódica cartesiana, la duda que revela al propio “yo” que duda?:', 'Método socrático', 'Método cartesiano', 'Método crítico', 'Método fenomenológico', 4],
['¿Cuál es la parte de la metafísica que trata del ser en general y de sus propiedades trascendentales? :', 'Hermenéutica', 'Ontología', 'Libertad', 'Mercancía', 2],
['El método _____________ significa interpretación. Hace referencia al arte o técnica de interpretar textos para fijar su verdadero sentido:', 'Hermenéutico', 'Ontología', 'Fenomenología', 'Psicología', 1],
['Es la demostración de la auto contradicción textual, una demostración que se apoya en el supuesto de una incompatibilidad en lo que el escritor cree y lo que el texto dice realmente:', 'Método desconstruccionalista', 'Método cartesiano', 'Método crítico', 'Método fenomenológico', 1],
['Filósofo que considera la dialéctica como un modelo según el cual debe constituirse el conocimiento correcto:', 'Nietzsche', 'Platón', 'Georg Wilhem', 'Karl Marx', 2],
['Filósofo que considera que la dialéctica es el pensamiento para comprender y mostrar a través de conceptos, el movimiento que realiza la historia de la humanidad:', 'Sartre', 'Ortega y Gasset', 'George Wilhem', 'Karl Marx', 3],
['Filósofo que considera que la dialéctica es un saber previo y más fundamental que la ciencia:', 'Aristóteles', 'Spinoza', 'Heidegger', 'Sartre', 1],
['Método que propone tres fases: el análisis socio histórico, el análisis discursivo y la interpretación:', 'Ciclo hermenéutico', 'Método de análisis del discurso', 'Método desconstruccionalista', 'Método fenomenológico', 2],
['Filósofo que considera que la dialéctica es materialista porque pone a la praxis, del actuar humano-social como la actividad que transforma y produce efectivamente lo real que convierte la realidad natural en realidad humana:', 'Seneca', 'Nietzsche', 'Georg Wilhem', 'Karl Marx', 4],
['¿Qué significa conocimiento adquirido a través de la experiencia? :', 'Trascendente', 'Empírico', 'Sintáctico', 'Pragmático', 2],
['¿Qué significa que esta más allá de los límites de cualquier conocimiento posible?:', 'Trascendente', 'Empírico', 'Sintáctico', 'Pragmático', 1],
['Método que supone que sólo tiene sentido hablar de aquello que puede ser observado y que por lo tanto solamente tienen sentido o significan los enunciados que pueden ser contrastados empíricamente:', 'Método ideológico', 'Método empírico', 'Método critico', 'Método de análisis del lenguaje', 4],
['La palabra epistemología proviene del griego episteme que significa:', 'Proceso', 'Ciencia', 'Ética', 'Estética', 2],
['¿Qué campo estudia la reflexión que busca determinar el ser de los entes, es decir, lo que los hace posibles?:', 'La epistemología', 'La ética', 'La ontología', 'La moral', 3],
['¿Qué se refiere al análisis de las tres formas del pensamiento: concepto, juicio y razonamiento? :', 'Lógica', 'Ciencia', 'Cultura', 'Filosofía', 1],
['Cuando se presentan razones a favor o en contra de un juicio se habla de:', 'Filosofía de la religión', 'De un concepto', 'De gnoseología', 'El razonamiento o argumento', 1],
['Estudia el comportamiento moral de los seres humanos y los fundamentos que se consideran bueno o moralmente correcto:', 'Ética', 'Estética', 'Valores', 'Conocimiento', 1],
['Se aboca especialmente al estudio de la relación  que establece los seres humanos con sus deidades, los valores que se le  son propio y el de los fines o consecuencias de sus prácticas.', 'Filosofía de la religión', 'Filosofía de la ciencia', 'Filosofía política', 'Filosofía de la cultura', 1],
['Investiga el desarrollo el cambio del conocimiento científico y de la práctica científica y su relación con la realidad:', 'Filosofía de la religión', 'Filosofía de la ciencia', 'Filosofía política', 'Filosofía de la cultura', 2],
['Según Marx, ¿cuál es la principal razón por la que la clase obrera sufre un proceso de alienación?', 'No es dueño de su trabajo', 'Está supeditado a ideas religiosas', 'No puede participar en la vida política', 'Ninguna de las respuestas es correcta', 1],
['Centra su atención en las costumbres, tradiciones, hábitos y expresiones artísticas, religiosas, morales, jurídicas entre otras en su unidad como un todo de los diversos pueblos:', 'Filosofía de la religión', 'Filosofía de la ciencia', 'Filosofía política', 'Filosofía de la cultura', 1],
['Significa razonamiento lógico que deriva de dos premisas:', 'Prerrogativa', 'Axiología', 'Ética', 'Silogismo', 4],
['Fue el principal exponente de la corriente del pensamiento empírico:', 'David Hume', 'Rene descartes', 'Francis Bacon', 'Platón', 1],
['El aporte______________ a la gnoseología moderna es la aplicación del razonamiento matemático al análisis de la realidad material, de las matemáticas como garantía de verdad y validez lógica:', 'cartesiano', 'del leguaje', 'de análisis', 'hermenéutico', 1],
['Considera los sentidos como las herramientas adecuadas para adquirir conocimientos se niega la intuición intelectual aceptando solo la intuición sensible:', 'La impresión de ideas', 'Silogismo', 'La tesis', 'El empirismo', 4],
['Según Hume pensar significa:', 'Tener ideas', 'Ser intelectual', 'Relacionar ideas entre sí', 'Sentir', 4],
['¿Quién es el padre de la filosofía occidental?', 'Platón', 'Descartes', 'Pitágoras', 'Aristóteles', 1],
['En el mito de la caverna de Platón, las cadenas representan:', 'Los sentidos', 'Las ideas', 'El cuerpo', 'El alma', 1],
['Platón hace la distinción de dos mundos en:', 'Mundo de los pensamientos y mundo sensible', 'Mundo sensible y  mundo de las ideas', 'Mundo sensitivo y mundo de las ideas', 'Mundo del cuerpo y mundo del alma', 2],
['Para Marx, ¿Cuál es el objetivo prioritario de la filosofía?', 'Relacionarse con Dios', 'Cambiar el mundo', 'Conocer los procesos que rigen el conocimiento', 'Establecer las normas y usos comunes de la moral', 2],
['Para Platón el conocimiento debe ir:', 'De lo general a lo particular', 'De lo particular a lo universal', 'De lo universal a lo particular', 'De una idea general a una cosa concreta', 2],
['Según Platón, ¿Cuál es la primera de las ideas?', 'La idea de Justicia', 'La idea de Bien', 'Dios', 'La moral', 2],
['Para Platón la polis será justa si:', 'Si los gobernantes gobiernan a los guardianes y a los productores', 'Si no existen distinciones entre guardianes, gobernantes y productores', 'Si los guardianes gobiernan la polis', 'La polis nunca llegará a ser justa totalmente', 1],
['Para Platón, el gobierno más apropiado para que se dé la justicia en el Estado es:', 'La democracia', 'La timocracia', 'La aristocracia', 'La oligarquía', 2],
['La teoría hilemórfica dice que…', 'La materia es aquello a partir de lo cual se individualiza la forma', 'La forma [substancial] se corresponde con la naturaleza o la esencia de cada cosa', 'La materia y la forma están íntimamente relacionadas', 'Ninguna de las respuestas es correcta.', 3],
['Aristóteles define una realidad…', 'Dual', 'Única', 'Diferenciada entre lo sensible y lo racional', 'Incognoscible', 2],
['Aristóteles afirma que el ser es:', 'Materia que se corresponde con el acto y forma que corresponde al ser en potencia.', 'Materia y forma y también en acto y  en potencia', 'Solo en acto y en potencia', 'Solo materia y forma', 2],
['Según Aristóteles el primer motor inmóvil es:', 'Dios', 'Acto puro, o causa encausada que dinamiza el universo', 'No existe un primer motor inmóvil', 'Una solución vaga al problema del movimiento', 2],
['La concepción aristotélica de la realidad es:', 'Sustancial', 'Accidental', 'Teleológica', 'Teológica', 3],
['Todo movimiento está motivado por una causa, y en la producción de cualquier ser intervienen:', 'Cuatro causas: dos intrínsecas [material  y formal] y dos extrínsecas [eficiente y final]', 'Dos causas: material y formal', 'Dos causas: una intrínseca y una extrínseca', 'Cuatro causas: dos intrínsecas [acto y potencia] y dos extrínsecas [material y formal]', 1],
['Aristóteles propone una epistemología capaz de:', 'Generalizar lo individual a lo universal', 'Conocer las substancias primeras a partir de las substancias segundas', 'Abstraer lo universal de lo individual', 'Ninguna es correcta', 3],
['Aristóteles distingue cuatro niveles de conocimiento:', 'Sentimiento, imaginación, experiencia y entendimiento', 'Imaginación, sensación, experiencia y conocimiento', 'Sensación, imaginación, experiencia y entendimiento', 'Pensamiento, imaginación, experiencia y entendimiento', 3],
['Para Aristóteles el fin último del ser humano es:', 'Alcanzar el conocimiento', 'La felicidad', 'Ser virtuoso', 'Alcanzar el bien común', 2],
['Aristóteles diferenció tres tipos de alma:', 'Vegetativa, sensitiva e intelectiva', 'Vegetativa, racional y sensorial', 'Sensorial, racional e intelectual', 'Volitiva, sensitiva y racional', 1],
['¿Quién afirmó que el ser humano es social por naturaleza?', 'Platón', 'Aristóteles', 'Hume', 'Sócrates', 2],
['Según Aristóteles las virtudes se alcanzan:', 'Mediante la contemplación', 'Por la actividad intelectual', 'Mediante el hábito y la contemplación', 'Se desarrollan con el tiempo mediante la actualización de las potencialidades', 3],
['Para Kant, ¿cuáles son las condiciones de posibilidad de existencia de todos los fenómenos?:', 'Las ideas a posteriori', 'Las ideas innatas', 'Las sensaciones', 'El tiempo y el espacio', 4],
['¿Quién es el último de los filósofos antiguos?', 'Santo Tomás', 'San Agustín', 'Descartes', 'Aristóteles', 2],
['¿Cuál de las siguientes afirmaciones sobre los juicios analíticos no es correcto?', 'Son universales', 'Son a posteriori', 'Son independientes de la experiencia', 'Son verdaderas en todos los casos', 2],
['Según San Agustín el libre albedrio…', 'No existe', 'Es un don que nos da Dios para que podamos elegir entre el camino del bien y el camino del mal', 'Es diferente de la auténtica libertad', 'Se identifica  con la tendencia a pecar', 2],
['Según Santo Tomás, la verdad:', 'Es única', 'No es una, sino que se distinguen las verdades de fe y de razón', 'Es doble, coincide con el pensamiento del averroísmo latino', 'No se puede alcanzar', 1],
['Para Santo Tomás, Dios rige el mundo mediante:', 'La ley Eterna', 'La ley positiva', 'La ley natural', 'Ninguna de las respuestas es cierta', 1],
['El método que propone Descartes deberá cumplir con cuatro reglas:', 'La evidencia, el análisis, la síntesis y la enumeración', 'La intuición, el análisis, la enumeración y la síntesis', 'El análisis, el razonamiento,  la enumeración y  la síntesis', 'El  razonamiento, la enumeración, la síntesis y el análisis', 1],
['¿En qué consiste la duda metódica?', 'Consiste en cuestionar todos nuestros conocimientos sin ninguna finalidad.', 'Consiste en analizar la realidad para llegar a verdades universales', 'Consiste en cuestionar todos nuestros conocimientos a fin de hallar alguno que sea seguro e indudable.', 'Consiste en dudar de todo lo exterior a uno mismo.', 3],
['Descartes plantea las siguientes razones para dudar:', 'El engaño del mundo y la distinción del sueño y la vigilia.', 'La existencia de un genio maligno y el engaño de los sentidos.', 'El engaño de los sentidos, la imposibilidad de distinguir la realidad de la vigilia o del sueño y la hipótesis del genio maligno.', 'Los sentidos y sensaciones nos confunden en nuestro conocimiento de la realidad.', 3],
['¿Quién hizo la siguiente afirmación: “Pienso luego existo”?', 'Aristóteles', 'Hume', 'Sócrates', 'Descartes', 4],
['Descartes investiga el origen de las ideas y las diferencia en:', 'Externas, internas e innatas', 'Adventicias, facticias e innatas.', 'Res cogitans, res extensa y res infinita', 'Aprendidas, innatas e individuales', 3],
['¿Qué utiliza Descartes para demostrar la existencia de Dios?', 'El yo infinito y contingente', 'La res extensa', 'La existencia del alma', 'La misma idea innata de Dios.', 4],
['La unión del cuerpo y el alma se encuentra según Descartes en:', 'En el cerebro', 'La glándula pineal', 'No se puede identificar una zona concreta', 'No existe distinción alma-cuerpo.', 2],
['Para Descartes, en el ser humano:', 'El cuerpo es la cárcel del alma', 'No existe diferencia entre alma y cuerpo', 'Coinciden alma y cuerpo en una unión accidental.', 'No puede existir la libertad.', 3],
['Para Descartes, las pasiones deben ser sometidas a la razón por medio de', 'La voluntad', 'La justicia', 'La libertad', 'La prudencia', 4],
['Hume hace una distinción de las percepciones en:', 'Impresiones e ideas', 'Sensaciones y pensamientos', 'Ideas y sensaciones', 'De sensación y de reflexión', 4],
['¿Cuál de los siguientes filósofos es empirista?', 'Descartes', 'Hume', 'Santo Tomas', 'Nietzsche', 4],
['¿En qué consiste el criterio de validez del conocimiento de Hume?', 'Afirmar que la verdad se encuentra en las sensaciones, en lo que podemos experimentar.', 'Poder afirmar de que impresión o impresiones deriva una idea.', 'Es la capacidad para relacionar ideas', 'Toda impresión se relaciona con una idea', 2],
['Para Kant son válidos los juicios:', 'Sintéticos a posteriori', 'Analíticos a priori', 'Sintéticos a priori', 'Analíticos a posteriori', 3],
['Según Hume, establecemos relaciones entre los fenómenos por:', 'Conocimiento', 'Hábito o costumbre', 'Experiencia', 'Relación causal entre fenómenos', 2],
['¿Quién escribió “La crítica de la razón pura”?', 'Descartes', 'Locke', 'Kant', 'Marx', 3],
['Para Kant, ¿cuáles son los postulados de la razón práctica?', 'La materia y la forma', 'Virtud y felicidad', 'La libertad, la inmortalidad del alma y la existencia de Dios', 'La verdad y el conocimiento', 3],
['¿Quien afirma la muerte de Dios?', 'Nietzsche', 'Marx', 'Kant', 'Wittgenstein', 1],
['El imperativo categórico es uno de los elementos centrales de la ética de:', 'Santo Tomás', 'Marx', 'Kant', 'Hume', 3],
['Para Marx el auténtico conocimiento es:', 'La actividad teórica', 'La actividad práctica', 'La praxis.', 'Se encuentra en el mundo de las ideas', 3],
['¿Qué significa el concepto de eterno retorno propuesto por Nietzsche?', 'Es una metáfora que utiliza para explicar que este mundo es finito.', 'Toda la realidad vuelve hacia la primera causa encausada.', 'Dios es la primera causa de la que se derivan todas las demás.', 'Todos los sucesos de la realidad se repiten eternamente.', 4],
['¿Cuál era la ciencia social por la que más se sentía atraído Ortega y Gasset?', 'Historia', 'Pedagogía', 'Sociología', 'Psicología', 1],
['¿Qué dice la teoría de la reminiscencia de Platón?', 'Nuestras almas sólo tienen que recordar aquello que ya han visto en el mundo de las ideas, pues de él provienen todas las almas.', 'El cuerpo impide que podamos recordar el conocimiento del mundo de las ideas.', 'El alma recuerda todo lo relativo al mundo de las ideas', 'La teoría de la reminiscencia no es de Platón sino de Aristóteles', 1],
['¿Dentro de que corriente filosófica puede englobarse a Ortega y Gasset?', 'Empirismo lógico', 'Estructuralismo', 'Perspectivismo', 'Dogmatismo', 3],
['Platón nació en:', 'Atenas', 'Estagira [Macedonia]', 'Roma', 'Esmira', 1],
['Según Aristóteles, la polis o Estado es anterior a los individuos y a los demás niveles de asociación humana, pues es la forma más perfecta de comunidad y sólo en ella puede el ser humano alcanzar su _________ llevando una vida adecuada a la ________.', 'Potencialidad, virtud', 'Felicidad, justicia', 'Bien, sociedad', 'Libertad, bondad', 2],
['¿En qué época nació Platón?', 'En el S. II a.C', 'En el S. IV a.C', 'En el S. V a.C', 'En el S. II a.C', 2]
];

var preguntasLengua = [
['“Cartas Marruecas” es una obra de:', 'Cadalso', 'Calderón de la Barca', 'El Marqués de Villena', 'Ninguno de estos autores', 1],
['Gaspar Melchor de Jovellanos vivió entre los años:', '1750-1798', '1790-1850', '1800-1850', '1744-1811', 4],
['La Real Academia Española es fundada en el año:', '1713', '1815', '1750', '1850', 1],
['La Real Academia Española es fundada por:', 'Felipe V', 'El Marqués de Villena', 'Felipe IV', 'Ninguno de estos ilustres', 2],
['“Los Pazos de Ulloa” es una obra escrita por:', 'Emilia Pardo Bazán', 'Benito Pérez Galdós', 'Emile Zola', 'Alas Clarín', 1],
['¿Cuál de los siguientes no es un autor realista español?', 'Juan Valera', 'Jose María de Pereda', 'Benito Pérez Galdós', 'García Lorca', 4],
['Leopoldo Alas Clarín fue el autor de:', 'La Regenta', 'Guerra y Paz', 'Amadeo I', 'Casanova', 1],
['La obra “Guerra y Paz” se le atribuye a:', 'Leon Tolstoi', 'Charles Dickens', 'Fedor Dostoievski', 'Ninguno de estos autores', 1],
['Los principios teóricos del naturalismo literario fueron expuestos por:', 'Émile Zola', 'Fedor Dostoievski', 'Leon Tolstoi', 'Charles Dickens', 1],
['“El trovador” es una obra de:', 'Antonio María Gutiérrez', 'Rosalía de Castro', 'Gustavo Adolfo Bécquer', 'Ninguno de estos autores', 1],
['“Don Juan Tenorio” es una obra de:', 'José Zorrilla', 'Rosalía de Castro', 'Gustavo Adolfo Bécquer', 'Ninguno de estos autores', 1],
['Rosalía de Castro fue autora de novelas de estilo:', 'Novelístico', 'Romántico', 'Poético', 'Drama', 2],
['Gustavo Adolfo Bécquer vivió y murió entre los años:', '1825-1870', '1850-1895', '1835-1975', '1836-1870', 4],
['Grandes temas del romanticismo literario:', 'Muerte', 'Naturaleza', 'Vida', 'Todas las respuestas son correctas', 4],
['¿Qué obra literaria introdujo el romanticismo en España?', 'Los prometidos', 'La mirada', 'Don Álvaro o la fuerza del Sino', 'A Jarifa en una orgía', 3],
['El romanticismo literario surge en:', 'Alemania', 'Francia', 'España', 'Inglaterra', 1],
['El romanticismo literario surge en el siglo:', 'XX', 'XIX', 'XVIII', 'XXI', 2],
['Dos aspectos fundamentales de la concepción romántica son:', 'Exaltación de la libertad y los sentimientos personales', 'La exaltación de la libertad y del amor', 'La pasión y el amor libre', 'El sentimentalismo y la expresión', 1],
['La obra ”El sí de las niñas”, está escrita en:', 'Verso', 'Prosa', 'Poesía', 'Novela', 2],
['La obra “El sí de las niñas” tiene como temas fundamentales:', 'Derecho a la libertad de elegir pareja y educación de la mujer', 'La política y la sociedad', 'La educación de la mujer y el adulterio', 'El Adulterio y la libertad en el amor', 1],
['La técnica esperpéntica se inicia con la obra:', 'Luces de Bohemia', 'Claves líricas', 'Sí, soy Guiomar', 'Ninguna de las respuestas es cierta', 1],
['Obra más relevante de Leandro Fernández de Moratín:', 'Cantos de sirenas', 'En el encinar', 'Las señoritas', 'El sí de las niñas', 4],
['Ramón Valle-Inclán destaca por ser:', 'Novelista', 'Poeta', 'Ensayista', 'Todas las respuestas son ciertas', 4],
['Pío Baroja pertenece a la generación:', 'Del 14', 'Del 21', 'Del 98', 'Del novecentismo', 3],
['Antonio Machado se dedicó principalmente a:', 'Política', 'Poesía', 'Lírica', 'Teatro', 2],
['Ramiro de Maeztu destacó principalmente por:', 'Poesía', 'Ensayos', 'Música', 'Arte', 2],
['“Don Quijote, Don Juan y la Celestina” es una obra de:', 'Lorca', 'Machado', 'Maeztu', 'Baroja', 3],
['“San Manuel bueno, mártir” es una novela de:', 'Miguel de Unamuno', 'Pio Baroja', 'Ramiro de Maeztu', 'Antonio Machado', 1],
['Quién es el autor de la obra literaria “Azul”?', 'Federico García Lorca', 'Rubén Darío', 'Pío Baroja', 'Ramiro de Maeztu', 2],
['¿De dónde es Rubén Darío?', 'Nicarágua', 'Argentina', 'Guatemala', 'México', 1],
['¿Cómo murió Federico García Lorca?', 'Se suicidó', 'De una enfermedad', 'Asesinado', 'De un accidente de tráfico', 3],
['“Miau”, de Benito Pérez Galdós, es una novela:', 'Realista', 'Surrealista', 'Poética', 'Teatral', 1],
['Rubén Darío es la figura clave del:', 'Modernismo', 'Realismo', 'Surrealismo', 'Impresionismo', 1],
['¿Cuál de las siguientes obras es de Camilo José Cela?', 'La familia de Pascual Duarte', 'La sombra del ciprés es alargada', 'El marqués de Barradomín', 'Tiempo de silencio', 1],
['Federico García Lorca nació y murió entre los años:', '1850-1925', '1878-1938', '1898-1936', '1895-1935', 3],
['“Los intereses creados” es una obra de:', 'Jacinto Benavente', 'Álvarez Quintero', 'Pedro Muñoz Seca', 'Ramón del Valle-Inclán', 1],
['La obra “El marqués de Bradomín” de Valle-Inclán, dramatiza el tema de:', 'La Guerra civil española', 'El adulterio', 'La muerte', 'La religión', 2],
['La producción poética de Dámaso Alonso inicia con:', 'Hijos de la ira', 'Hombre y Dios', 'Poemas puros', 'No se dedicó a la poesía', 3],
['Principales movimientos de la vanguardia Europea:', 'Realismo, cubismo, dramatismo, expresionismo', 'Futurismo, cubismo, expresionismo, dadaísmo, surrealismo', 'Todas las respuestas son ciertas', 'No fueron vanguardistas', 2],
['La figura clave de la vanguardia española fue:', 'Gabriel Miró', 'Ramón Pérez de Alaya', 'Ortega y Gasset', 'Ramón Gómez de la Serna', 4],
['El género preponderante de la generación del 14 fue:', 'El ensayo', 'La lírica', 'El drama', 'La sátira', 1],
['Ortega y Gasset pertenece a:', 'Generación 98', 'Generación del 27', 'El Novecentismo', 'Generación 27', 3],
['La generación del 14 es también conocida como:', 'El boom', 'Novecentismo', 'Los intelectuales', 'Los conservadores', 2],
['La novela testimonial consiste en:', 'Relatos y testimonios de personajes públicos', 'Autobiografías de autores', 'Relatos realistas sobre problemas sociales', 'Historias de gente del pueblo', 3],
['El autor de “Cien años de soledad” es:', 'Juan Rulfo', 'Mario Vargas Llosa', 'Miguel Unamuno', 'Gabriel García Márquez', 4],
['Qué novela narra la historia de Juan Preciado?', 'Cien años de soledad', 'El Llano  en llamas', 'Pedro Páramo', 'El coronel no tiene quien le escriba', 3],
['Miguel Ángel Asturias era de origen:', 'Guatemalteco', 'Argentino', 'Peruano', 'Español', 1],
['La novela hispanoamericana de los años 60 es también conocida como:', 'Depresiva', 'Boom', 'Crash', 'Divertida', 2],
['¿Cuál de los siguientes autores fue Premio Nobel de literatura en 2010?', 'Rubén Darío', 'Mario Vargas Llosa', 'Gabriel García Márquez', 'Julio Cortázar', 2],
['En la narrativa hispanoamericana, los años 40 del siglo XX fueron de:', 'Decadencia', 'Invención', 'Renovación', 'Creatividad', 3],
['EL realismo mágico es un elemento de:', 'Poesía Hispanoamericana', 'Narrativa Hispanoamericana', 'Teatro Hispanoamericano', 'Ninguna de las respuestas es correcta', 2],
['“Los novísimos” eran:', 'Un grupo de poetas españoles', 'Un género literario que inventaron a finales del siglo XX', 'Un grupo de escritores del siglo XX', 'Una banda musical de los años 90', 1],
['La poesía arraigada y desarraigada pertenecen a la década de:', 'Los 40', 'Los 50', 'Los 60', 'Los 70', 1],
['En la poesía de los años 50 tuvo gran influencia:', 'Pablo Neruda', 'Antonio Machado', 'Miguel Hernández', 'Todos ellos', 4],
['Los rasgos de la Generación del 36 se caracterizan por:', 'El dolor, la muerte y la esperanza por la vida', 'Alegría y sencillez para esconder el dolor por la guerra civil.', 'Profundo lirismo, la preocupación por el hombre y su realidad y el estilo sencillo y pulcro.', 'Ninguna de las respuestas es cierta', 3],
['Uno de los dramaturgos más representativos del teatro en la década de los 60-70 es:', 'José Sanchís Sinisterra', 'Fermin Cabal', 'Fernando Arrabal', 'Miguel Mihura', 3],
['Quién escribió el libro “La casa de Bernarda Alba”?', 'Federico García Lorca', 'Pio Baroja', 'Miguel Unamuno', 'Ninguno de ellos', 1],
['“Tres sombreros de copa” es una obra de:', 'Antonio Buero Vallejo', 'Miguel Mihura', 'Edgar Neville', 'Alfonso Sastre', 2],
['Definición de onomatopeya:', 'Letra inicial de una palabra', 'Palabras tomadas de otras lenguas', 'Formación de palabras por imitación de los ruidos naturales', 'Reducción de una palabra', 3],
['¿De qué se constituye una palabra derivada?', 'De un solo monema', 'Consta de dos o más lexemas', 'Combinan un lexema con uno o varios afijos', 'Es un caso especial de mezcla de composición y derivación', 3],
['¿Qué es el complemento indirecto?', 'Concreta el significado del verbo en las estructuras transitivas', 'Expresa la persona, animal o cosa que se beneficia o perjudica de la acción del verbo', 'Señala circunstancias que inciden en la acción verbal', 'Expresa una cualidad del sujeto', 2],
['¿Qué es el sujeto omitido?', 'Cuando al emitir un enunciado no expresamos el sujeto porque lo sobreentendemos', 'Cuando al emitir un enunciado no aparece el verbo', 'Cuando hay varios sujetos', 'Cuando hay un complemento', 1],
['¿Qué es el sintagma adjetival?', 'Conjunto de palabras que tiene como núcleo un verbo', 'Conjunto de palabras que tiene como núcleo un adverbio', 'Conjunto de palabras que tiene como núcleo un sintagma nominal', 'Conjunto de palabras que tiene como núcleo un adjetivo calificativo', 4],
['¿Qué es el sintagma nominal?', 'Grupo de palabras cuyo núcleo es el sustantivo, nombre o cualquier otro elemento que equivalga a un sustantivo', 'Grupo de frases cuyo núcleo es el complemento', 'Grupo de palabras cuyo núcleo es una perífrasis', 'Ninguna de las respuestas es válida', 1],
['¿Qué tipos de oración gramatical existen?', 'Enunciativas, exclamativas, desiderativas, dubitativas, imperativas e interrogativas', 'Negativas, imperativas, desiderativas, de opinión, interrogativas y exclamativas', 'Enunciativas, de resultado, negativas, interrogativa, dubitativas y exclamativas', 'Desiderativas, negativas, positivas, enunciativas, imperativas e interrogativas', 1],
['¿Qué es una oración dubitativa?', 'Su finalidad es informar al destinatario', 'El emisor expresa incertidumbre, por lo que no asume la total veracidad del contenido del enunciado', 'Intentan influir en el receptor a través de enunciados impositivos', 'Presentan el contenido del enunciado con deseable o conveniente', 2],
['¿Qué es la isotopía?', 'Consiste en la dependencia gramatical entre las diferentes unidades que componen un texto', 'Consiste en reemplazar un elemento por otro', 'Consiste en la repetición de unidades lingüísticas relacionadas entre sí por su forma o significado', 'Consiste en proporcionar instrucciones para la distribución de los comentarios', 3],
['¿Qué se entiende por elipsis?', 'Son los adverbios de tiempo', 'Omisión de un elemento del enunciado que se sobreentiende', 'Repetición de sonidos', 'Son los pronombres especializados en sustituir a sustantivos', 2],
['¿Qué es la deixis?', 'Un mecanismo lingüístico que señala quién, dónde y cuándo', 'Un mecanismo lingüístico que señala la intención del texto', 'Un mecanismo lingüístico que remite que alude a algo enunciado con anterioridad', 'Un mecanismo lingüístico que se encarga de la coherencia del texto', 1],
['¿Cuáles son las partes constitutivas más importantes de un texto?', 'La intención', 'El enunciado y el párrafo', 'Las perífrasis', 'El párrafo y los conectores', 2],
['El texto según su modalidad se puede clasificar en:', 'Argumentativo, crítico, narrativo, descriptivo y analista', 'Descriptivo, analista, argumentativo, noticioso y prescriptivo', 'Descriptivo, expositivo, narrativo, argumentativo y prescriptivo', 'Narrativo, idealista, autobiográfico, prescriptivo y argumentativo', 3],
['¿Qué significa que una palabra es antónima?', 'Palabras que tienen pertenecen a la misma categoría gramatical', 'Palabras que se escriben igual', 'Palabras con significados opuestos', 'Palabras que se coinciden los referentes a través de una perífrasis', 3],
['¿Qué es una palabra homónima?', 'Palabra en la que a su significante le corresponden varios significados', 'Palabra que no tiene significado', 'Palabra en la que a su significante le corresponde un solo significado', 'Palabra que en el pasado tenían significado y significantes distintos, pero que ahora tienen un significante que se escribe igual o parecido y se pronuncia igual', 4],
['¿Qué es la denotación?', 'Es el significado objetivo de una palabra, aparece en los diccionarios y es común a todos los hablantes de una lengua.', 'Es el significado subjetivo de una palabra, aparece en los diccionarios y es común a todos los hablantes de una lengua.', 'Es el significado subjetivo de una palabra y es común a todos los hablantes de una lengua.', 'Es el significado objetivo de una palabra y no aparece en los diccionarios', 1],
['¿Qué son los neologismos?', 'Palabras provenientes del Neolítico', 'Palabras nuevas que nacen', 'Palabras que caen en desuso', 'Palabras cultas', 2],
['Las palabras según su formación se dividen en:', 'Simples, compuestas y derivadas', 'Simples, parasintéticas y derivadas', 'Negativas, simples y compuestas', 'Cuantitativas, cualitativas y derivadas', 1],
['Tipos de estructura de los textos científicos:', 'Deductiva, inductiva, encuadrada y paralela', 'Inductiva, paralela, analítica y triangular', 'Deductiva, expositiva, encuadrada y triangular', 'Deductiva, inductiva, analítica y paralela', 1],
['¿Qué son los marcadores o conectores textuales?', 'Palabras o locuciones que relacionan oraciones, párrafos o apartados de un texto', 'Son proposiciones que se mantienen aisladas', 'Es una forma narrativa', 'Ninguna de las respuestas es correcta', 1],
['¿Qué tipo de textos son los más objetivos?', 'Jurídicos', 'Científicos', 'Poéticos', 'Narrativos', 2],
['¿Qué es la función fática del lenguaje?', 'Es la que centra la atención de la comunicación en el emisor', 'Es la que centra la atención de la comunicación en el canal', 'Es la que centra la atención de la comunicación en el mensaje', 'Es la que centra la atención de la comunicación en el receptor', 2],
['¿Qué es la función apelativa del lenguaje?', 'Es la que centra la atención de la comunicación en el emisor', 'Es la que centra la atención de la comunicación en el canal', 'Es la que centra la atención de la comunicación en el mensaje', 'Es la que centra la atención de la comunicación en el receptor', 4],
['Todo texto debe cumplir tres propiedades. ¿Cuáles son?', 'Coherencia, adecuación y cohesión', 'Corrección, subjetividad y apreciación', 'Coherencia, apreciación y estilo', 'Estilo, cohesión y adecuación', 1],
['¿Cuál es la definición de oración?', 'Unidad lingüística dotada de significación que no pertenece a una unidad lingüística superior.', 'Unidad lingüística perteneciente a otras unidades lingüísticas', 'Sintagma o agrupación de palabras en torno a un núcleo', 'Unidad lingüística que carece de significado', 1],
['La Oda es:', 'Una forma narrativa', 'Una forma literaria', 'Una forma dramática', 'Ninguna es correcta', 2],
['El poema épico es:', 'Una forma narrativa', 'Una forma literaria', 'Una forma dramática', 'Ninguna es correcta', 3],
['La comedia es:', 'Una forma narrativa', 'Una forma literaria', 'Una forma dramática', 'Ninguna es correcta', 3],
['La égloga es:', 'Una forma narrativa', 'Una forma literaria', 'Una forma dramática', 'Ninguna es correcta', 2],
['La epopeya es:', 'Una forma narrativa', 'Una forma literaria', 'Una forma dramática', 'Ninguna es correcta', 1],
['En la narrativa:', 'El autor-narrador se sitúa como espectador', 'El autor-narrador forma parte de la obra', 'El autor-narrador hace un escrito autobiográfico', 'El autor-narrador cuenta una noticia de actualidad', 1],
['La forma de discurso que corresponde a la dramática es:', 'Explicativo', 'Expositivo', 'El diálogo', 'Ninguna de es correcta', 3],
['En el género literario lírico predomina:', 'La objetividad', 'La subjetividad', 'La improvisación', 'La inmediatez', 2],
['¿Cuáles son los géneros literarios?', 'La lírica, la poesía y el teatro', 'La Lírica, la dramática y la narrativa', 'La narrativa, la noticia y la lírica', 'La dramática, la poesía y  la opinión', 2],
['¿Qué elementos intervienen en el lenguaje literario?', 'Emisor, receptor, canal, contexto y mensaje', 'Emisor, receptor,  mensaje, lector y comunicación', 'Lector, receptor , canal y comunicación', 'Todas las respuestas son falsas', 1],
['¿Cuáles son las características del lenguaje periodístico?', 'Claridad, precisión, intensidad y brevedad', 'Claridad, precisión, brevedad y objetividad', 'Precisión, intensidad, objetividad e intensidad', 'Subjetividad, claridad, precisión y brevedad', 2],
['¿Qué son los géneros de opinión?', 'Son los que ofrecen información sobre un hecho de actualidad', 'Son los que se  hacen mediante encuestas', 'Son  los que ofrecen análisis subjetivos, interpretaciones argumentadas y juicios de valor sobre hechos de actualidad', 'Son los que ofrecen un análisis objetivo sobre hechos pasados', 3],
['¿De qué tipo puede ser una entrevista?', 'Biográfica o informativa', 'Informativa o explicativa', 'Expresiva o biográfica', 'Opinativa o expresiva', 1],
['¿En qué partes se estructura una noticia?', 'Titular, lead o entrada y cuerpo', 'Entrada, cuerpo y final', 'Titular y cuerpo', 'Entrada, subtítulo y cuerpo', 1],
['¿Cuáles son los géneros periodísticos mixtos?', 'El artículo de opinión y el reportaje', 'La crónica y la entrevista', 'La columna y la noticia', 'La crónica y la crítica', 4],
['¿Cuáles son los géneros periodísticos de opinión?', 'El editorial, el reportaje y la columna', 'El editorial, el artículo de opinión y las cartas al director', 'El artículo de opinión, las cartas al director y la entrevista', 'El reportaje, el editorial y la crónica', 2],
['¿Cuáles son los géneros periodísticos informativos?', 'La noticia, el reportaje y la entrevista', 'La noticia, el reportaje y la columna', 'La noticia, la crónica y la entrevista', 'La entrevista, el reportaje y el editorial', 1]
];

var preguntasIngles = [
['He gave up ______ last month.', 'to smoke', 'that he would smoke', 'smoking', 'smoke', 3],
['Where do you think ______ next summer?', 'are you going to be', 'you will be', 'you are being', 'will you be', 2],
['It ______ when we were in Burgos this morning, so we couldn’t visit Atapuerca.', 'was raining', 'has rained', 'has been raining', 'would rain', 1],
['Mary ______ me to lend her my class notes! She doesn’t attend many classes.', 'asks always', 'always is asking', 'is always asking', 'had been always asking', 3],
['Choose the correct option.', 'She’s very keen to Formula 1.', 'He’s quite keen with Formula 1.', 'I’m very keen on Formula 1.', 'None of the options are correct.', 3],
['Dad told Mom that...', 'he would always help her.', 'he helped her for good.', 'he is helping her for good.', 'None of the options are correct.', 1],
['Choose the correct option.', 'If we finish on time, we go to the party.', 'Had we finished on time, we would have gone to the party.', 'Whether we finished on time, we will go to the party.', 'None of the options are correct.', 2],
['Choose the correct option.', 'How long is it to Malaga?', 'How much to Malaga?', 'How far are we from Malaga?', 'None of the options are correct.', 3],
['Choose the correct option.', 'You didn’t have to do that, you know.', 'You needn’t do that, you know.', 'You didn’t do that, you know.', 'All of the options are correct.', 4],
['Choose the correct option. [Answer:  Not till next year]', 'Is Sarah going school?', 'Is Sarah going to school?', 'Does she like school?', 'None of the options are correct.', 2],
['Choose the correct option.', 'Are you studied French last summer?', 'Are you studying Chinese last summer?', 'Have you studied French last summer?', 'None of the options are correct.', 4],
['Choose the correct option.', 'I don’t think they will ever arrive on time.', 'I think they are never arriving on time.', 'I think they are never arrived on time.', 'None of the options are correct.', 1],
['Choose the correct option.', 'Rachel has never been into India.', 'Rachel has never gone into India.', 'He’s gone often in India.', 'None of the options are correct.', 4],
['Choose the correct option.', 'I’m trying to doing some sport every week.', 'I try to playing soccer every week-end.', 'I’m trying to eat a healthier menu in restaurants.', 'None of the options are correct.', 3],
['Choose the correct option.', 'I am usually having some bread with my lunch.', 'I am used to have some bread with my lunch.', 'I usually have some bread with my lunch.', 'None of the options are correct.', 3],
['Choose the correct option.', 'I work next Saturday.', 'I don’t work next Saturday.', 'I’m working next Saturday.', 'All of the responses are correct.', 4],
['Choose the correct option.', 'When are you going to visit me?', 'When going to visit me are you?', 'When do you visit me?', 'None of the options are correct.', 1],
['I’ve made up my mind! ______ 8 hours every day the week before my Physics exam.', 'I’m going to study', 'I’m practicing', 'I study', 'I shall practice', 1],
['He refused _________ a doctor. He said he only needed to rest a bit.', 'going to', 'to see', 'to be seeing', 'go', 2],
['If Kate __________ for that job, she would have got it.', 'has tried', 'has been trying', 'had applied', 'Applied', 3],
['An important part of the process is to ________ your work at the end.', 'revised', 'review', 'check', 'glance over', 3],
['I don’t know if I can go to Mallorca. It depends __________ how much money I spend this summer.', 'if', 'in', 'of', 'on', 4],
['Where __________? You look very handsome now.', 'did you have your hair cut', 'do you went to cut your hair', 'did you cut your hair', 'does your hair have been cut', 1],
['Sorry! We’ve __________ milk. Would you prefer some tea?', 'split up with', 'run out of', 'run away from', 'missed', 2],
['The Twin Towers were the __________ buildings in the USA.', 'taller', 'higher', 'most tall', 'highest', 4],
['Yesterday, I __________ a ‘Castle’ episode on TV.', 'looked', 'was looking', 'watched', 'see', 3],
['The actress was dressed __________ a colourful costume.', 'in', 'on', 'by', 'with', 1],
['Bob __________ at home all day. Is he ill?', 'has stood', 'hasn’t been staying', 'has stayed', 'was staying', 3],
['I feel tired and sad! I might have __________ a cold!', 'got', 'caught', 'had', 'earned', 2],
['You __________ to the concert. It was quite exciting!', 'mustn’t have gone', 'should go', 'may go', 'ought to have gone', 4],
['Does anybody know __________?', 'where he works', 'where does he work', 'where works he', 'where he does work', 1],
['David is working really __________ this morning.', 'strong', 'hard', 'hardly', 'strongly', 2],
['Last month, my daughter __________ back to Brazil.', 'had gone', 'took', 'flied', 'went', 4],
['Paul is really friendly and __________.', 'intelligent', 'selfish', 'outgoing', 'rude', 3],
['Pete knew a little French so he ______ to ask for food in Paris restaurants.', 'can', 'could', 'was able', 'Succeeded', 3],
['Frodo, ______ best friend was Sam, arrived at Mordor just in time to win the war.', 'whose', 'who’s', 'who', 'which', 1],
['Bill’s wallet ______ while he was in the disco last night.', 'stole', 'was robbed', 'robbed', 'was stolen', 4],
['Adam ______ green tea when he visited Ireland last autumn.', 'used to drinking', 'got used to drink', 'was used to drink', 'got used to drinking', 4],
['[Nadal won the match against Murray]. The match against Murray ______ by Nadal.', 'was won', 'is won', 'was win', 'had been win', 1],
['[The manager postponed the training session until Monday] Tito ______ the training session until Monday.', 'put over', 'put after', 'put off', 'put down', 3],
['Ma Baker used force and a gun to enter the bank. Ma Baker ______ into the bank with a gun.', 'went', 'jumped', 'slipped', 'broke', 4]
]